### ISSUE TITLE
可以搞个搜索接口吗？

### ISSUE THREAD

**Issue by chenxuuu** [JxiaoC/animeMusic#1]
就是按歌名/动画名来搜索歌曲的接口
我想搞到[https://github.com/chenxuuu/24h-raspberry-live-on-bilibili](https://github.com/chenxuuu/24h-raspberry-live-on-bilibili)这个上面用用，来搞事情吗😉

**Comment by JxiaoC** [comment]
https://github.com/JxiaoC/animeMusic#搜索歌曲动漫

之前写了接口忘了完善文档

**Comment by chenxuuu** [comment]
啊。。谢谢。。。等我有空加一下吧，带封面这个参数好评
