### ISSUE TITLE
JiJiDown新版本Crash

### ISSUE THREAD

**Issue by xtexx** [JxiaoC/animeMusic#4]
好歹留个邮箱啊

发生了预料之外的错误:
System.Windows.Markup.XamlParseException: 在“System.Windows.StaticResourceExtension”上提供值时引发了异常。 ---> System.ArgumentOutOfRangeException: 意外的类型 ID 31487。类型 ID 必须按顺序排列。
参数名: typeId
   在 System.Windows.Baml2006.Baml2006SchemaContext.AddXamlType(Int16 typeId, Int16 assemblyId, String typeName, TypeInfoFlags flags)
   在 System.Windows.Baml2006.Baml2006Reader.Process_TypeInfo()
   在 System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   在 System.Windows.Baml2006.Baml2006Reader.ReadObject(KeyRecord record)
   在 System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   在 System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   在 System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   在 System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   在 System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   在 System.Windows.ResourceDictionary.FetchResource(Object resourceKey, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean canCacheAsThemeResource, Boolean& canCache)
   在 System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
   在 System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   在 System.Windows.StaticResourceExtension.ProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference)
   在 System.Windows.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   在 System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   在 System.Windows.Application.DoStartup()
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

重新安装时setup也会crash
![image](https://user-images.githubusercontent.com/46394906/88358455-9d420600-cda1-11ea-9730-58dc34e19a49.png)

**Comment by xtexx** [comment]
连个联系方式都没有

**Comment by JxiaoC** [comment]
http://clientfile.jijidown.com/PC/WPF/HistoricVersion/WPF_JJDown_v1.225.0.zip

**Comment by xtexx** [comment]
压缩文件已损坏
![image](https://user-images.githubusercontent.com/46394906/88361632-4857bd00-cdac-11ea-90ab-d3828a6ac603.png)

**Comment by JxiaoC** [comment]
测试了下，解压正常，文件MD5 60D9EDF1E3BD0BD05703F30FE2B87339

**Comment by xtexx** [comment]
> 测试了下，解压正常，文件MD5 60D9EDF1E3BD0BD05703F30FE2B87339

你想多了, 
```
MD5 哈希(文件 WPF_JJDown_v1.225.0.zip):
9e ac c4 a5 64 ff af 86 e1 43 55 39 51 57 f9 c3
CertUtil: -hashfile 命令成功完成。
```
![image](https://user-images.githubusercontent.com/46394906/88362264-6aead580-cdae-11ea-8e54-9e7f32911b85.png)

**Comment by xtexx** [comment]
大小8,761,862 字节

**Comment by JxiaoC** [comment]
![{AEC677D8-EC16-425A-907B-FB494D9DC0D0}_20200724140502](https://user-images.githubusercontent.com/6435789/88364810-b73a1380-cdb6-11ea-9b10-e29ec15918c7.jpg)
你这哈希结果都不正常

**Comment by JxiaoC** [comment]
还有，你的这种沟通方式，很让人感到不舒服，我不欠你的。

**Comment by xtexx** [comment]
> 还有，你的这种沟通方式，很让人感到不舒服，我不欠你的。

嗯好的, 但是我还是不明白为什么我下载了这么多次还是哈希不正常
